In [ ]:
#配列（ディクショナリ、リスト、タプル、セット）
#ディクショナリ{:,:},リスト[], タプル(), セット{}
#ディクショナリは、キーがリストのインデックス番号と同じと考えると良い
#while文を使えば、「条件を満たしている間」同じ処理を繰り返し行えます。
#while 条件式:
 #   条件を満たしている間、繰り返す処理
#while文もfor文と同様、break文やcontinue文が使える
#break文：繰り返し処理の途中で強制終了し、ループから抜け出す命令
#continue文：繰り返し処理の途中で中断し、次のループに進む命令
#関数、関数名(引数):で関数を定義。関数を呼び出すときは、関数名(引数に代入するもの)で呼び出す
#クラスのイメージ。クラス名は、変数に代入して使う感じ。そして、変数.属性とかで色々できるイメーj
#クラス；属性の部分では、インスタンス化する時の引数を決めている。
#クラス内の属性と、メソッドへのアクセス方法は変わらない。扱い的には、属性は変数、メソッドは関数のイメージ
#Pythonのスライシング[0:4]、使うのは:

In [ ]:
#applyメソッド
#作成した関数を、データフレームの要素等に適応するためのメソッド。
#applyの引数の中に関数の名前が入って、関数の引数には、適応しているデータフレームの各要素が入ってくるということ.
#今回なら、applyでtax関数を呼び出して、tax関数の引数には、df['単価']の各要素が入ってくるということ
#def tax(x):
#    return x * 1.10
#df['単価'].apply(tax)


In [1]:
import numpy as np
A=np.array([[0,1],[2,3],[4,5]])
B=np.array([[0,1,2,3],[4,5,6,7]])
result=np.dot(A,B)
print("行列の積の結果:\n", result)
max_value=np.amax(result)
max_value

行列の積の結果:
 [[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47

NameError: name 'CD' is not defined